name: "Bug Report"
title: "[Bug Report] "
description: "Report the issue you're experiencing."
projects: []
labels:
  - Bug
body:
  - type: textarea
    id: textarea-0
    attributes:
      label: Describe the bug
      description: Report the issue you're experiencing.
      value: |-
        ### Title:
        _A short, clear summary of the issue._

        ### Description:
        _A detailed explanation of what's going wrong._

        ### Steps to Reproduce:
        _How did you get the error to occur?_

        ### Expected Behavior:
        _What you thought should happen._

        ### Actual Behavior:
        _What actually happened._

        ### Additional Context:
        _Anything else that might help identify or reproduce the issue._
    validations:
      required: true
