name: Update Corps & Alliances JSON

on:
  schedule:
    - cron: "0 * * * *"   # runs every hour
  workflow_dispatch:       # optional manual trigger

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install node-fetch@3

      - name: Run update script
        run: node scripts/update-data.js

      - name: Commit & push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add alliances.json corporations.json
          git commit -m "Update alliances and corps (automated)" || echo "No changes"
          git push
